### ISSUE TITLE
Add more languages to syntax highlighting

### ISSUE THREAD

**Issue by shnupta** [shnupta/bric#1]
Check out the [syntax modules wiki](https://github.com/shnupta/bric/wiki/Modules#syntax) and add a few more languages and keywords to existing languages.

Languages needed are:
- [x] Javascript
- [x] C#
- [x] Java
- [ ] HTML (might be harder)
- [x] PHP
- [x] Pascal
- [x] SQL
- [x] Go
- [x] Rust
- [x] Ruby

**Comment by shnupta** [comment]
http://misc.flogisoft.com/bash/tip_colors_and_formatting

Perfect for terminal colouring.

**Comment by sadboyzvone** [comment]
I'll check this out

**Comment by sadboyzvone** [comment]
I added PHP however I'm not seeing changes when I compile the code

**Comment by shnupta** [comment]
@sadboyzvone 
The `#define` that you did in the php.h file needs to be inside the `highlight_db` array in syntax.h.

**Comment by sadboyzvone** [comment]
Oh thanks,by the way is it okay if I add more languages like Pascal,SQL and others?

**Comment by shnupta** [comment]
@sadboyzvone Yeah sure add as many as you like! Also if you are interested there is another issue open about adding a new feature - #9

**Comment by sadboyzvone** [comment]
Yes I noticed! I've been also looking at your repos and noticed the HexBueno one. It sounded interesting are you still planning to work on it? If not I would like to try to make something similar

**Comment by shnupta** [comment]
@sadboyzvone Yeah I still plan to work on it at some stage. I think, however, I may incorporate into bric a hex viewing mode instead of starting a new editor from scratch as quite a bit of the code can be used again (but I haven't decided yet). Just use it like `bric --hx <filename>` or something like that. But tomorrow I go back to school and have exams in a month so trying not to program too much at the moment haha!

**Comment by sadboyzvone** [comment]
Yeah me too! But I still program too much for my own good haha :)

**Comment by shnupta** [comment]
@sadboyzvone Yup same here haha!
