### ISSUE TITLE
Host the demo gif somewhere other than this git repo

### ISSUE THREAD

**Issue by shnupta** [shnupta/bric#125]
No need for it to be in here, and it means it takes a long time for first time clones.

**Comment by sexybiggetje** [comment]
Unless you put it in a branch 'graphics' / 'docs' or something similar. Or perhaps use gh-pages?

**Comment by andy5995** [comment]
>Unless you put it in a branch 'graphics' / 'docs' or something similar. Or perhaps use gh-pages?

I tried gh-pages but it's not working.

The code from the README

```
### Here is a screencast of bric on macOS:
![Screencast](https://andy5995.github.io/screencast_low.gif)
```

But then the image doesn't show up on the README, just a link, and the link leads to

https://camo.githubusercontent.com/cfeb1f9c715df4e110da78040e4ed94f155166c0/68747470733a2f2f616e6479353939352e6769746875622e696f2f73637265656e636173745f6c6f772e676966

And when I click it, I get a blank page except for this message: "Content length exceeded
"

I'm just going to put a link on the README for now. That should also help speed up load time for users when viewing the main repo page/README file online.
