### ISSUE TITLE
Fix tab length

### ISSUE THREAD

**Issue by shnupta** [shnupta/bric#133]
When setting `tab_length` in the config file, and then pressing tab inside the editor it doesn't move the correct amount of spaces. E.g. if I set it to `4` in the config, it moves `3` spaces.

I've tested on Manjaro Linux, would anybody be able to confirm this on other OSs?

**Comment by andy5995** [comment]
For me, on Debian 9, it works as intended. I tried with 4 and 10.

**Comment by shnupta** [comment]
Ended up being my terminal settings.
