### ISSUE TITLE
Configure the Makefile to build to new build dir

### ISSUE THREAD

**Issue by shnupta** [shnupta/bric#134]
The docs now inform the user that they should create a build directory with `mkdir build` however the build process doesn't actually output the compiled files to this directory.

**Comment by andy5995** [comment]
I forgot to add one step. After making the build directory

cd build

then running ../configure and make will put the build files in build

**Comment by timpratim** [comment]
I am new to open source contributions but I want to help. Could you please help me and let me know what exactly is to be done

**Comment by andy5995** [comment]
Thank you for the offer, @timpratim . There is actually a PR  I submitted that's almost done being tested and we'll likely be merging it. You're welcome to [join the bric chat room](https://join.slack.com/t/bric-editor/shared_invite/enQtNDIyNjg5NzY2MTQ1LTk4OTE4ZjdiMGFmMDlhNWM2ZWJkMmM0MGQxMjNhODJlOWY1MjQzMmQ5MDEzOGM3YjM0YTJiZTc3MWY5MGNmZjI). We'll likely have more issues opening over the next few months.
