### ISSUE TITLE
Hungarian translation needed

### ISSUE THREAD

**Issue by epresi** [shnupta/bric#154]
The instructions for translators are at https://github.com/shnupta/bric/blob/master/TRANSLATE.md

The file that need translating is https://github.com/shnupta/bric/blob/master/po/bric.pot but please view the instructions first!

**Comment by epresi** [comment]
Please assign it to me! Thx

**Comment by andy5995** [comment]
Completed by @epresi in https://github.com/shnupta/bric/commit/b151adfefd03f1a3cf0b255e2316dc92e565eb8a
