### ISSUE TITLE
Customizable tab spacing

### ISSUE THREAD

**Issue by shnupta** [shnupta/bric#17]
Add a config file to enable users to change tab width.

**Comment by Ekrips** [comment]
Hi,
this is my first contribution to an open-source project, and I hope what i did was fine. I tried to be explicit in the commit message.

I have an issue though : I cloned the repository and made my changes, but git will not let me push ("Permission denied to..."). I think I'm supposed to make a pull request but I'm not sure how I'm supposed to do that. Could you please help me ?

**Comment by shnupta** [comment]
Hi there,

Yeah sure! So what you should do is first fork this repository to your own
profile. There is a fork button in the top right of this repository's home
page. Then you will have your own version of bric as Ekrips/bric.

Then you should clone that repository and commit and push your changes to
there. Once you have implemented the feature you can then submit a pull
request to this repository from your repository.

Hope this helps, let me know if you need anything else. Happy
contributing!:)

On 9 May 2017 3:17 p.m., "Ekrips" <notifications@github.com> wrote:

Hi,
this is my first contribution to an open-source project, and I hope what i
did was fine. I tried to be explicit in the commit message.

I have an issue though : I cloned the repository and made my changes, but
git will not let me push ("Permission denied to..."). I think I'm supposed
to make a pull request but I'm not sure how I'm supposed to do that. Could
you please help me ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/shnupta/bric/issues/17#issuecomment-300179159>, or mute
the thread

**Comment by Ekrips** [comment]
Thank you, I think I did it !

**Comment by shnupta** [comment]
Merged in #21
