### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by grikukan** [shnupta/bric#18]
When editing large files (> 100mb) some operations can be really slow. Probably it can be fixed by storing rows and texts in rows in linked lists instead of arrays.

**Comment by shnupta** [comment]
Okay I will check this out. Send me an email (address is on my profile) and I will add you to the slack chat.

**Comment by DreamTheater2016** [comment]
I'd like to work on this. I think we should also have a small cache of pointers to the current line, the next line, and the previous line.

**Comment by shnupta** [comment]
Closed in PR #63
