### ISSUE TITLE
Segfaults when newline at start

### ISSUE THREAD

**Issue by NanoPish** [shnupta/bric#26]
On Ubuntu 16.04 I got a segfault when I open a new file and press newline.

It seems to come from a uninitialized string sent to strlen line 653 in editor_insert_newline, created in get_indent_prefix.

**Comment by shnupta** [comment]
Okay thanks for letting me know! I'm currently in the middle of a big refactor (vim-refactor branch) so when I'm all done I'll get round to fixing it.
