### ISSUE TITLE
Problem with some commentaries delimiter

### ISSUE THREAD

**Issue by RomainStasyszyn** [shnupta/bric#29]
In fact, the code is think for commentary token // and /* */ but for Python there is # and "" """ and for Ruby there is # and =begin =end. I tested the commentary highlighting with Python and Ruby monoline and multiline but no one work. I am working on it to try to be more general about commentary token gestion.

**Comment by shnupta** [comment]
Okay sounds good, submit a PR when you are ready! Thanks:)

**Comment by RomainStasyszyn** [comment]
I'll do it during June, for May i'm very busy....

**Comment by shnupta** [comment]
I believe this is fixed in latest commit on vim-change branch
