### ISSUE TITLE
Indent maintainer has trouble when pasting

### ISSUE THREAD

**Issue by shnupta** [shnupta/bric#33]
Seems to auto indent almost every line when pasting in.

**Comment by bleepcord** [comment]
I have a simple pull request with a fix that comes from vim. (set paste and unset paste commands). If you are looking for a more complex solution to the problem let me know and I can start working on it. Perhaps temporarily disabling auto indenter automatically when pasting in?

**Comment by shnupta** [comment]
This has been closed in PR #50 by bleepcord
