### ISSUE TITLE
Organise Code

### ISSUE THREAD

**Issue by shnupta** [shnupta/bric#37]
Make sure all current code sticks to one code style (this code styling will be documented).

Add more commenting to parts of the code which are slightly harder to grasp quickly.

Overall, just make the code easier to read and understand before continuing with the refactor.

**Comment by rafaelcn** [comment]
I would vote to place every source code of bric inside a `src` folder. And then divide the `bric.c` into files in which each file does a specific function, like loading the config file. We could implement a generic file loader and then pass the config file to it, it would return a structure like a hash-map or a simple dictionary for easy iteration. More things could be split from `bric.c`.

**Comment by shnupta** [comment]
@rafaelcn So sorry I haven't seen your comment. Your suggestion seems like a good idea, if you like feel free to comment on the Road Ahead issue to further discuss your ideas - #67

**Comment by andy5995** [comment]
Hi @rafaelcn 

>I would vote to place every source code of bric inside a src folder. 

Some of that's already been done now, and also is part of a separate ticket #72 

As for the source code style, we're going with GNU style. I ran this on most of the code today and committed changes.

`indent -ci2 -bl -bli0 -nut`
