### ISSUE TITLE
Editor size should be flexible

### ISSUE THREAD

**Issue by Abhishek-Kuvalekar** [shnupta/bric#40]
Maximizing terminal after opening bric in default size doesn't change the size of the editor.

**Comment by shnupta** [comment]
Something may be able to be implemented from what is discussed here:

https://stackoverflow.com/questions/31619962/vt100-ansi-escape-sequences-getting-screen-size-conditional-ansi

**Comment by DreamTheater2016** [comment]
I just fixed the bug and submitted a pull request. :)

**Comment by shnupta** [comment]
Thanks @DreamTheater2016 :)
