### ISSUE TITLE
Error with absolute path

### ISSUE THREAD

**Issue by doztrock** [shnupta/bric#78]
Hello!

Today I was trying to implement a little feature and I've realized something.

I've "checkouted" my repository version to the last commit, after:

`make clean all`
`sudo make install`

I've installed `bric` in my computer, after I've tried to edit a file in an absolute path (e.g.):

`bric /home/doztrock/Desktop/file.txt`

BUT!

At the footer, there's a message:

`/home =- 0 lines                                                                                                       1/0`
`Normal mode.`

I've written some text inside the editor, and, I've gotten the following error:

`Cannot save! I/O error: Is a directory`

I think there's a problem with the  absolutes path, anyway, I'll try to find and correct the issue if possible, ASAP.

Regards.

P.S. Please confirm you've gotten the same error, maybe my computer is asking for a replacement. :)

**Comment by doztrock** [comment]
I am checking my code, I think there's a problem with my commit `9ed927e`.

**Comment by doztrock** [comment]
@shnupta I am really sorry about this issue, It was my fault, there was a problem with the pointers used in the global variable struct __current file. I've took some time in my country it's 2:09, but I've solved it!

https://github.com/shnupta/bric/pull/79

I hope you could test the correction, and merge it.

Regards

P.S. Sorry again

**Comment by shnupta** [comment]
Hi @doztrock ,

No worries about the issue, it shows we need a testing phase too before we finally merge PRs. I can also recreate this issue on my machine. I'll take a look at the PR now:)
